version: "3.9"

x-aws-cluster: le-club
x-aws-vpc: vpc-f1af5599

services:

  application:
    command: start
    healthcheck: 
      test: ["CMD-SHELL", "curl --fail http://localhost/api/.well-known/openid-configuration || exit 1"]
    image: 052941667971.dkr.ecr.eu-west-3.amazonaws.com/le-club-auth:latest
    env_file: .env.staging
    ports: 
      - "80:80"