version: "3.9"

services:

  application:
    build: 
      context: .
      dockerfile: Dockerfile.local
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: start
    env_file: .env.local
    volumes: 
      - ./src:/usr/home/leclub/src
    networks: 
      - le-club-api_network
    ports: 
      - "8081:8081"

  database:
    env_file: .env.local
    image: mongo:5.0.2
    networks:
      - le-club-api_network
    ports:
      - "27019:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${LCB_ACCOUNTS_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${LCB_ACCOUNTS_DATABASE_PASSWORD}

networks:
  le-club-api_network:
    external: true