export const intialStateCoach = {
  _id: '1234',
  firstName: 'idriss ',
  lastName: 'diallo',
  email: 'eded@gmail.com',
  role: 15,
  club: 1,
  users: [],
  currentTeam: {},
  currentVideo: {},
  currentMatch: {},
  currentCuts: [],
  prefStudio: {},
  currentVideoDrawing: {},
  keyTeam: 0,
  keyDays: 0,
  keyMatch: 0,
  favoriteTeam: null,
  isAuthenticated: true,
  trainings: [],
  currentTraining: {},
  keyTraining: 0,
  urlLogo: '',
  urlCover: '',
  playerCoached: [],
  trainedTeam: [],
  succesTitle: '',
  succesValue: '',
  biographie: '',
  phisolophie: '',
  favoriteCoach: '',
  playerCareer: '',
  subscribeAt: null,
  subscribeType: '',
  stripeId: '',
  cancelSubscription: null,
  disabledPrivateActivate: null,
  futurAccountType: null,
  isAdminManaged: false,
  createdAt: null,
  hideSequencageTry: false,
  parrainageToken: null,
  parrainagePopup: null,
  parrainageSeason: [],
  cagnotte: 0,
  pushToken: '',
  presequencageTutorial: null,
}

export const initialStateSeasons = {
  seasons: ['test'],
  currentSeason: 1,
  club: {test:'test'},
  team: {test:'test'},
}

export const initialStateMobile = {
  pushToken: '',
  isOnMobile: '',
  isOnIOS: '',
}
