version: "3.9"

services:

  app:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: watch
    env_file: 
      - .env.local
    volumes: 
      - ./src:/usr/home/leclub/src
      - ./bin:/usr/home/leclub/bin
    networks: 
      - network
    ports: 
      - "8080:8080"

  database:
    env_file:
      - .env.local
    image: mongo:5.0.2
    networks:
      - network
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${LCB_API_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${LCB_API_DATABASE_PASSWORD}

networks:
  network:
    driver: bridge